server:
  port: 8082   # You can change this to any available port

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rewardly_employee_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  application:
    name: Rewardly-Employee-Service
