server:
  port: 8082

spring:
  profiles:
    active: local

  sql:
    init:
      mode: NEVER 
#     To avoid duplication use mode never  mode: NEVER, data.sql file
#     mode: always
#			To initalize as application started   mode: always, data.sql file

