server:
  port: 8082

spring:
  profiles:
    active: local

  sql:
    init:
      mode: NEVER 
#     To avoid duplication of inserting data in database use  mode: NEVER, data.sql file
#     mode: always
#			To initalize or insert data into database as application started use   mode: always, data.sql file

